# Generated by Django 4.0.10 on 2023-07-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restauration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_du_jour', models.TextField()),
                ('plat', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('option_vegetarien', models.BooleanField(default=False)),
                ('option_vegan', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='menu_images/')),
                ('option_livraison', models.BooleanField(default=False)),
                ('adresse_livraison', models.TextField(blank=True, null=True)),
                ('horaires_retrait', models.CharField(blank=True, max_length=100, null=True)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('preferences_speciales', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('preparation', 'En préparation'), ('livre', 'Livrée'), ('retire', 'Retirée')], default='en_attente', max_length=20)),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('date_livraison', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
