# Generated by Django 4.0.10 on 2023-07-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cours', models.CharField(choices=[('piano', 'Piano'), ('batterie', 'Batterie'), ('guitare', 'Guitare'), ('flute', 'Flûte'), ('danse', 'Danse')], max_length=20)),
                ('horaires', models.CharField(max_length=100)),
                ('duree', models.DurationField()),
                ('disponibilite', models.BooleanField(default=True)),
                ('cout', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
