# Generated by Django 4.0.10 on 2023-07-18 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('control_user', '0002_profilartiste_utilisateur_delete_customuser'),
        ('evenement', '0002_streamingendirect_programme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_billets', models.PositiveIntegerField()),
                ('cout_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut_paiement', models.BooleanField(default=False)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evenement.evenement')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_user.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_paiement', models.CharField(max_length=100)),
                ('transaction_reussie', models.BooleanField(default=False)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.ImageField(upload_to='qr_codes/')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservation.reservation')),
            ],
        ),
    ]
