# Generated by Django 4.0.10 on 2023-07-18 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_user', '0003_utilisateur_groups_utilisateur_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='user_permissions',
        ),
    ]
